[common]
dependencies = [
    "voir>=0.2.19,<0.3",
    "torch",
    "PyYAML",
    "argklass",
    "fairscale",
    "torchtune @ git+https://github.com/meta-pytorch/torchtune.git@50a2b8f",
    "accelerate",
    "transformers",
    "torchvision",
    "fire",
    "blobfile",
    "torchao",
]

[cuda]
dependencies = [
]

[rocm]

[xpu]
enabled = false
