_inference:
  inherits: _defaults
  definition: .
  install-variant: unpinned
  install_group: torch


whisper-transcribe-single:
  inherits: _inference
  num_machines: 1
  tags:
    - multigpu
  plan:
    method: per_gpu

  argv:
    --model: 
    --dataset:
    --batch-size:


txt-to-image-gpus:
  inherits: _inference
  num_machines: 1
  tags:
    - multigpu
  plan:
    method: njobs
    n: 1

  argv:
    --model: 
    --dataset:
    --batch-size: