[common]
dependencies = [
    "voir>=0.2.19,<0.3",
    "torch",
    "datasets",
    "transformers",
    "diffusers",
    "argklass",
    "accelerate",
    "cantilever",
    "sentencepiece",
    "protobuf",
]

[cuda]
dependencies = [
    "torchcodec",
]

[rocm]
enabled = true

[hpu]
enabled = false

[xpu]
enabled = false
