

_lightning:
  inherits: _defaults
  definition: .
  install-variant: unpinned
  install_group: torch
  argv:
    --epochs: 10
    --num-workers: "auto({n_worker}, 8)"
    --loader: pytorch
    --data: "{milabench_data}/FakeImageNet"
    --model: resnet152

lightning:
  inherits: _lightning
  num_machines: 1
  plan:
    method: per_gpu
    n: 1

lightning-gpus:
  inherits: _lightning
  num_machines: 1
  plan:
    method: njobs
    n: 1

lightning-nodes:
  inherits: _lightning
  num_machines: 2
  plan:
    method: njobs
    n: 1
  
  requires_capabilities:
    - "len(nodes) >= ${num_machines}"
