
diffusion:
  inherits: _defaults
  definition: .
  install-variant: unpinned
  install_group: torch
  num_machines: 1
  plan:
    method: per_gpu

diffusion-gpus:
  inherits: _defaults
  definition: .
  install-variant: unpinned
  install_group: torch
  num_machines: 1
  plan:
    method: njobs
    n: 1

diffusion-nodes:
  inherits: _defaults
  num_machines: 2
  definition: .
  install-variant: unpinned
  install_group: torch
  plan:
    method: njobs
    n: 1
  
  requires_capabilities:
    - "len(nodes) >= ${num_machines}"
