defaults: &defaults
  dirs:
    code: ./_dev_{name}
    venv: venv/{name}
    data: data
    runs: runs

  venv:
    type: virtualenv

  plan:
    method: njobs
    n: 1

  voir:
    --stop: 10
    --forward:
      - "#stdout"
      - "#stderr"
      - "#end"
      - loss
      - compute_rate
      - train_rate
      - loading_rate
      - descr
      - progress
      - total
    --compute-rate: true
    --train-rate: true
    --loading-rate: true

benchmarks:
  {{STEM}}:
    <<<: *defaults

    definition: ./
