
rlhf-single:
  inherits: _defaults
  definition: .
  install-variant: unpinned
  install_group: torch
  plan:
    method: per_gpu

  argv:
    --output_dir: "{milabench_extra}/output"
    --model_name_or_path: EleutherAI/pythia-1b-deduped
    --per_device_train_batch_size: 64
    --logging_strategy: "no"
    --log_level: "critical"
    --bf16: true

rlhf-gpus:
  inherits: _defaults
  definition: .
  install-variant: unpinned
  install_group: torch
  plan:
    method: njobs
    n: 1

  argv:
    --output_dir: "{milabench_extra}/output"
    --model_name_or_path: EleutherAI/pythia-1b-deduped
    --per_device_train_batch_size: 64
    --bf16: true