[common]
dependencies = [
    "voir>=0.2.19,<0.3",
    "torch",
    "trl",
    "accelerate",
    "transformers",
    "datasets",
    "einops",
    "argklass",
]

[cuda]

[rocm]

[xpu]
enabled = false
