[common]
dependencies = [
    "voir>=0.2.19,<0.3",
    "torch",
    "vllm",
    "vllm[bench]",
    "vllm[audio]",
    "torchcodec",
]

[cuda]
dependencies = [
    "flashinfer-python",
    "flashinfer-cubin",
    # "flashinfer-jit-cache",
]

[rocm]

[hpu]
enabled = false

[xpu]
enabled = false
