resnet50:
  observations:
  - {batch_size: 1, cpu: 8, memory: 1215 MiB, perf: 81.17}
  - {batch_size: 1, cpu: 8, memory: 1215 MiB, perf: 82.84}
  - {batch_size: 2, cpu: 8, memory: 1239 MiB, perf: 162.05}
  - {batch_size: 2, cpu: 8, memory: 1237 MiB, perf: 165.44}
  - {batch_size: 4, cpu: 8, memory: 1333 MiB, perf: 310.95}
  - {batch_size: 4, cpu: 8, memory: 1331 MiB, perf: 319.86}
  - {batch_size: 8, cpu: 8, memory: 1521 MiB, perf: 604.88}
  - {batch_size: 8, cpu: 8, memory: 1489 MiB, perf: 616.25}
  - {batch_size: 16, cpu: 8, memory: 1953 MiB, perf: 1057.52}
  - {batch_size: 16, cpu: 2, memory: 1953 MiB, perf: 715.48}
  - {batch_size: 16, cpu: 4, memory: 1953 MiB, perf: 1076.59}
  - {batch_size: 16, cpu: 8, memory: 1953 MiB, perf: 1053.75}
  - {batch_size: 16, cpu: 16, memory: 1953 MiB, perf: 1056.4}
  - {batch_size: 16, cpu: 32, memory: 1955 MiB, perf: 1047.61}
  - {batch_size: 16, cpu: 8, memory: 1893 MiB, perf: 1095.7}
  - {batch_size: 16, cpu: 2, memory: 1893 MiB, perf: 651.1}
  - {batch_size: 16, cpu: 4, memory: 1893 MiB, perf: 1115.38}
  - {batch_size: 16, cpu: 8, memory: 1893 MiB, perf: 1098.51}
  - {batch_size: 32, cpu: 8, memory: 2817 MiB, perf: 1342.75}
  - {batch_size: 32, cpu: 8, memory: 2703 MiB, perf: 1580.77}
  - {batch_size: 64, cpu: 8, memory: 4277 MiB, perf: 1200.01}
  - {batch_size: 64, cpu: 8, memory: 4233 MiB, perf: 1418.85}
  - {batch_size: 96, cpu: 2, memory: 5909 MiB, perf: 692.09}
  - {batch_size: 96, cpu: 4, memory: 5909 MiB, perf: 1125.07}
  - {batch_size: 96, cpu: 8, memory: 5911 MiB, perf: 1117.13}
  - {batch_size: 96, cpu: 16, memory: 5913 MiB, perf: 1116.68}
  - {batch_size: 96, cpu: 32, memory: 5917 MiB, perf: 1087.66}
  - {batch_size: 128, cpu: 8, memory: 7425 MiB, perf: 972.95}
  - {batch_size: 128, cpu: 8, memory: 7257 MiB, perf: 1197.54}
  - {batch_size: 248, cpu: 2, memory: 13459 MiB, perf: 629.8}
  - {batch_size: 248, cpu: 4, memory: 13461 MiB, perf: 903.27}
  - {batch_size: 248, cpu: 8, memory: 13465 MiB, perf: 899.48}
  - {batch_size: 248, cpu: 16, memory: 13473 MiB, perf: 895.3}
  - {batch_size: 248, cpu: 32, memory: 13487 MiB, perf: 859.99}
version: 2.0
