resnet50:
  observations:
  - {batch_size: 1, cpu: 8, memory: 1215 MiB, perf: 81.17}
  - {batch_size: 2, cpu: 8, memory: 1239 MiB, perf: 162.05}
  - {batch_size: 4, cpu: 8, memory: 1333 MiB, perf: 310.95}
  - {batch_size: 8, cpu: 8, memory: 1521 MiB, perf: 604.88}
  - {batch_size: 16, cpu: 8, memory: 1953 MiB, perf: 1057.52}
  - {batch_size: 16, cpu: 2, memory: 1953 MiB, perf: 715.48}
  - {batch_size: 16, cpu: 4, memory: 1953 MiB, perf: 1076.59}
  - {batch_size: 16, cpu: 8, memory: 1953 MiB, perf: 1053.75}
  - {batch_size: 16, cpu: 16, memory: 1953 MiB, perf: 1056.4}
  - {batch_size: 16, cpu: 32, memory: 1955 MiB, perf: 1047.61}
  - {batch_size: 32, cpu: 8, memory: 2817 MiB, perf: 1342.75}
  - {batch_size: 64, cpu: 8, memory: 4277 MiB, perf: 1200.01}
  - {batch_size: 96, cpu: 2, memory: 5909 MiB, perf: 692.09}
  - {batch_size: 128, cpu: 8, memory: 7425 MiB, perf: 972.95}
version: 2.0
