resnet50:
  observations:
  - {batch_size: 1, cpu: 8, memory: 907 MiB, perf: 80.41}
  - {batch_size: 2, cpu: 8, memory: 907 MiB, perf: 163.77}
  - {batch_size: 4, cpu: 8, memory: 907 MiB, perf: 311.94}
version: 2.0
