resnet152-ddp-gpus:
  observations:
  - {batch_size: 0, cpu: 8, memory: 25995 MiB, perf: 1995.03}
resnet50:
  observations:
  - {batch_size: 1, cpu: 8, memory: 46041 MiB, perf: 78.92}
  - {batch_size: 2, cpu: 8, memory: 1237 MiB, perf: 159.82}
  - {batch_size: 2, cpu: 8, memory: 34611 MiB, perf: 161.62}
  - {batch_size: 4, cpu: 8, memory: 1331 MiB, perf: 315.69}
  - {batch_size: 4, cpu: 8, memory: 46041 MiB, perf: 308.07}
  - {batch_size: 8, cpu: 8, memory: 1489 MiB, perf: 603.96}
  - {batch_size: 8, cpu: 8, memory: 46041 MiB, perf: 602.72}
version: 2.0
