# FROM ubuntu:22.04

FROM nvidia/cuda:13.0.2-devel-ubuntu24.04


# Arguments
# ---------

# Use ofed_info -s to get your local version
ARG MOFED_VERSION=5.4-3.4.0.0
ARG CONFIG=all.yaml
ARG ARCH=cuda
ARG SELECT=""
ARG VARIANT=""

ENV MILABENCH_GPU_ARCH=$ARCH
ENV MILABENCH_CONFIG_NAME=$CONFIG
ENV MILABENCH_DOCKER=1
ENV MILABENCH_SELECT=$SELECT
ENV MILABENCH_VARIANT=$VARIANT


# Paths
# -----

ENV MILABENCH_CONFIG=/milabench/milabench/config/$MILABENCH_CONFIG_NAME
ENV MILABENCH_BASE=/milabench/envs
ENV MILABENCH_OUTPUT=/milabench/results/
ENV MILABENCH_ARGS=""

# Copy milabench
# --------------

WORKDIR /milabench
COPY . /milabench/milabench/

# Install Dependencies
# --------------------

#            curl: used to download anaconda and rust
#             git: used by milabench
#      libibverbs: used for infiniband
#           rustc: used by BERT models inside https://pypi.org/project/tokenizers/
# build-essential: for rust


ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y &&\
    apt-get install -y --no-install-recommends zip ssh rsync git build-essential curl python3 python3-virtualenv python-is-python3 python3-pip libgl1 libglib2.0-0 gcc g++ python3-dev &&\
    curl -o /etc/apt/trusted.gpg.d/mellanox.asc https://content.mellanox.com/ofed/RPM-GPG-KEY-Mellanox &&\
    curl -o /etc/apt/sources.list.d/mellanox.list https://linux.mellanox.com/public/repo/mlnx_ofed/${MOFED_VERSION}/ubuntu22.04/mellanox_mlnx_ofed.list &&\
    apt-get update -y                                       &&\
    apt-get install -y --no-install-recommends libibverbs1  &&\
    apt-get clean                                           &&\
    rm -rf /var/lib/apt/lists/*                             &&\
    curl https://sh.rustup.rs -sSf | sh -s -- -y

# ENV CUDA_HOME=/milabench/envs/venv/torch/lib/python3.12/site-packages/nvidia/cu13
ENV CUDA_HOME=/usr/local/cuda/
ENV PATH="$CUDA_HOME/bin:/root/.cargo/bin:${PATH}"
ENV XDG_CACHE_HOME=/milabench/envs/cache
ENV HF_HOME=/milabench/envs/cache
ENV TORCH_HOME=/milabench/envs/cache

# Install Milabench
# -----------------

ENV MILAENCH_ENV=/milabench/.env
RUN RUN curl -LsSf https://astral.sh/uv/install.sh | sh                 &&\
    virtualenv $MILAENCH_ENV                                            &&\
    $MILAENCH_ENV/bin/python -m pip install -U pip                      &&\
    $MILAENCH_ENV/bin/python -m pip install -U setuptools               &&\
    $MILAENCH_ENV/bin/python -m pip install -U poetry                   &&\
    $MILAENCH_ENV/bin/python -m pip install -e /milabench/milabench[cuda]    &&\
    $MILAENCH_ENV/bin/python -m pip cache purge

# Prepare bench
# -------------

# pip times out often when downloading pytorch
ENV PIP_DEFAULT_TIMEOUT=800

# https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list
#
#       7.5
# A100: 8.0,8.6
#       8.9
# H100: 9.0
# B100: 10.0,12 GB10: 12.1
#
ENV TORCH_CUDA_ARCH_LIST="7.5;8.0;8.6;8.9;9.0;10.0;12.0;12.1"
ENV MILABENCH_WHEELS=https://github.com/milabench/wheels/releases/expanded_assets/cu130-wheels

# If the wheels are available locally we can do something like below
# RUN --mount=type=bind,source=wheels,target=/tmp/wheels           \

# But we can also publish wheels to github and use those instead
RUN ln -s /milabench/.env/bin/milabench /usr/local/bin/milabench                                                                                             &&\
    MILABENCH_PIP_ARGS="--find-links,$MILABENCH_WHEELS" $MILAENCH_ENV/bin/milabench install --config $MILABENCH_CONFIG --base $MILABENCH_BASE ${MILABENCH_SELECT:+--select $MILABENCH_SELECT} ${MILABENCH_VARIANT:+--variant $MILABENCH_VARIANT} $MILABENCH_ARGS   &&\
    $MILAENCH_ENV/bin/milabench patch --venv $MILABENCH_BASE/venv/torch                                                                                    &&\
    python -m pip cache purge

# CMD milabench run
