FROM nvcr.io/nvidia/pytorch:24.02-py3

# Arguments
# ---------

# Use ofed_info -s to get your local version
ARG MOFED_VERSION=5.4-3.4.0.0
ARG CONFIG=standard.yaml
ARG ARCH=cuda

ENV MILABENCH_GPU_ARCH=$ARCH
ENV MILABENCH_CONFIG_NAME=$CONFIG
ENV MILABENCH_DOCKER=1

# Paths
# -----

ENV MILABENCH_CONFIG=/milabench/milabench/config/$MILABENCH_CONFIG_NAME
ENV MILABENCH_BASE=/milabench/envs
ENV MILABENCH_OUTPUT=/milabench/results/
ENV MILABENCH_ARGS=""

# Copy milabench
# --------------

WORKDIR /milabench
COPY . /milabench/milabench/

# Install Dependencies
# --------------------

#            curl: used to download anaconda and rust
#             git: used by milabench
#      libibverbs: used for infiniband
#           rustc: used by BERT models inside https://pypi.org/project/tokenizers/
# build-essential: for rust


ENV DEBIAN_FRONTEND=noninteractive
RUN cd $HOME                                                         &&
    rm -rf /milabench/env                                            &&
    pip install virtualenv                                           &&
    virtualenv --system-site-packages /milabench/env                 &&
    /milabench/env/bin/pip install -e milabench                      &&
    /milabench/env/bin/milabench install --use-current-env           &&
    /milabench/env/bin/pip uninstall torch torchvision torchaudio -y &&
    /milabench/env/bin/pip cache purge
