
FROM ubuntu:22.04

# Arguments
# ---------

ARG ARCH=rocm
ENV MILABENCH_GPU_ARCH=$ARCH

ARG CONFIG=standard.yaml
ENV MILABENCH_CONFIG_NAME=$CONFIG
ENV MILABENCH_DOCKER=1

ARG PYTHON="3.10"


# Paths
# -----

ENV MILABENCH_CONFIG=/milabench/milabench/config/$MILABENCH_CONFIG_NAME
ENV MILABENCH_BASE=/milabench/envs
ENV MILABENCH_ARGS=""
ENV MILABENCH_OUTPUT="$MILABENCH_BASE/runs"
ENV BENCHMARK_VENV="$MILABENCH_BASE/venv"

# Copy milabench
# --------------

WORKDIR /milabench
COPY . /milabench/milabench/


# Install Dependencies
# --------------------

#            curl: used to download anaconda
#             git: used by milabench
#           rustc: used by BERT models inside https://pypi.org/project/tokenizers/
# build-essential: for rust

RUN mkdir --parents --mode=0755 /etc/apt/keyrings                                                                                                                    &&\
    wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | gpg --dearmor | tee /etc/apt/keyrings/rocm.gpg > /dev/null                                                 &&\
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/amdgpu/6.2.4/ubuntu jammy main" |  tee /etc/apt/sources.list.d/amdgpu.list   &&\
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.2.4 jammy main" \| tee --append /etc/apt/sources.list.d/rocm.list &&\
    echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' \| tee /etc/apt/preferences.d/rocm-pin-600                                               &&\
    apt-get update            &&\
    apt-get install -y rocm-dev hipcc hip-runtime-amd rocminfo rocm-device-libs          &&\
    apt-get install -y git build-essential curl python3.10 python-is-python3 python3-pip libgl1-mesa-glx libglib2.0-0 gcc g++ python3-dev &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
    

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Install Milabench
# -----------------

RUN python -m pip install -U pip            &&\
    python -m pip install -U setuptools     &&\
    python -m pip install -U poetry         &&\
    python -m pip install -e /milabench/milabench/ &&\
    python -m pip cache purge


# Prepare bench
# -------------

# pip times out often when downloading pytorch
ENV PIP_DEFAULT_TIMEOUT=800
ENV ROCM_HOME="/opt/rocm"
RUN milabench install --config $MILABENCH_CONFIG --base $MILABENCH_BASE $MILABENCH_ARGS &&\
    python -m pip cache purge

CMD ["milabench", "run"]
