mila:
  ssh: mila
  remote_folder:~/scratch/jobrunner
  local_folder: .

  nodes:
    - name: RTX8000
    - name: V100
    - name: A100
    - name: A6000
    - name: L40S
    - name: H100

beluga:
  ssh: beluga
  account: rrg-bengioy-ad
  cpu: 125
  nodes: 
    - name: base
      cpu: 40
      ram: 186
      gpu:
        - name: V100
          ram: 16
          count: 4

cedar:
  ssh: cedar
  account: rrg-bengioy-ad

narval:
  ssh: narval
  account: rrg-bengioy-ad
  nodes: 
    - name: base
      cpu: 48
      ram: 498
      gpu:
        - name: A100
          ram: 40
          count: 4

roqual:
  ssh: roqual
  account: rrg-bengioy-ad


fir:
  ssh: fir
  account: rrg-bengioy-ad

nibi:
  ssh: nibi
  account: rrg-bengioy-ad
