[common]
dependencies = [
    "jax",
    "torch",
    "brax",
    "voir>=0.2.19,<0.3",
]

[cuda]
dependencies = [
    "jax[cuda{cuda_major}]",
]

[rocm]
dependencies = [
    "jax[rocm]",
]

[hpu]

[xpu]
