

_flops:
  inherits: _defaults
  definition: .
  group: flops
  install-variant: unpinned
  install_group: torch
  plan:
    method: per_gpu
  
  tags:
    - diagnostic
    - flops
    - monogpu
    - nobatch
  
  argv:
    --number: 30
    --repeat: 90


fp16:
  inherits: _flops

  argv:
    --number: 30
    --repeat: 10
    --m: 8192
    --n: 8192
    --dtype: fp16

bf16:
  inherits: _flops
 
  argv:
    --m: 8192
    --n: 8192
    --dtype: bf16

tf32:
  inherits: _flops
 
  argv:
    --m: 8192
    --n: 8192
    --dtype: fp32
    --tf32: true

fp32:
  inherits: _flops
 
  argv:
    --m: 256
    --n: 256
    --dtype: fp32  
