
resnet50:
  tags:
    - vision
    - classification
    - cnn
    - fp16
    - e2e

  mem:
    slope: 82
    intercept: 2728
    multiple: 16

resnet50-fp32:
  tags:
    - vision
    - classification
    - cnn
    - fp32
    - e2e

  mem:
    slope: 90
    intercept: 2985
    multiple: 16

efficientnet_b4:
  tags:
    - vision
    - classification
    - cnn
    - fp16
    - e2e
  
  mem:
    slope: 115
    intercept: 2765
    multiple: 16

efficientnet_b7:
  tags:
    - vision
    - classification
    - cnn
    - fp16
    - e2e

  mem:
    slope: 264
    intercept: 3236
    multiple: 16

convnext_large:
  tags:
    - vision
    - classification
    - cnn
    - fp16
    - e2e

  mem:
    slope: 190
    intercept: 4090
    multiple: 16

regnet_y_128gf:
  tags:
    - vision
    - classification
    - cnn
    - fp32
    - lstm
    - e2e

  mem:
    slope: 826
    intercept: 5290
    multiple: 16

bert:
  tags:
    - nlp
    - language-modeling
    - transformer
    - no-io
    - huggingface

  mem:
    slope: 1000
    intercept: 3774
    multiple: 8

t5:
  tags:
    - nlp
    - language_modeling
    - transformer
    - huggingface
    - no-io

  mem:
    slope: 2683
    intercept: 1916
    multiple: 8

reformer:
  tags:
    - nlp
    - language-modeling
    - transformer
    - huggingface
    - no-io

  mem:
    slope: 385
    intercept: 1464
    multiple: 8

resnet152:
  tags:
    - vision
    - classification
    - convnet

  mem:
    slope: 4.23
    intercept: 3323
    multiple: 16

accelerate:
  tags:
    - LLM
