defaults: &defaults
  install_variant: "{arch}"

  voir:
    options:
      stop: 60
      interval: "1s"

sb3: &sb3
    <<<: *defaults

    group: sb3

    plan:
      method: njobs
      n: 1

    definition: ../benchmarks/stable_baselines3


benchmarks:
  ppo:
    <<<: *sb3
    tags:
      - rl

    argv:
      --algo: ppo
      --env: HalfCheetahBulletEnv-v0
      -n: '-1'
      --num-threads: '-1'
      --seed: '0'
      --vec-env: subproc
      --device: auto
      --: [-params, n_envs:16, n_steps:512, n_epochs:20, n_timesteps:50000]

  td3:
    <<<: *sb3
    tags:
      - rl

    argv:
      --algo: td3
      --env: HalfCheetahBulletEnv-v0 # Default: CartPole-v1
      --n-eval-envs: '1'
      --n-timesteps: '50000' # Default: '-1'
      --num-threads: '-1'
      --log-interval: '-1'
      --eval-episodes: '5'
      --save-freq: '-1'
      --seed: '0' # Default: -1
      --vec-env: subproc # Default: dummy
      --device: auto
      --n-trials: '10' # Default: 500
      --n-jobs: '1'
