include:
  - base.yaml

#################
# Enabled tests #
#################

reformer:
  enabled: true
  weight: 1.0

bert-tf32-fp16:
  enabled: true
  weight: 1.0

llm-lora-single:
  enabled: true
  weight: 1.0

llm-lora-ddp-gpus:
  enabled: true
  weight: 1.0

llm-lora-ddp-nodes:
  enabled: true
  weight: 2.0

llm-lora-mp-gpus:
  enabled: true
  weight: 1.0

llm-full-mp-gpus:
  enabled: true
  weight: 1.0

llm-full-mp-nodes:
  enabled: true
  weight: 3.0

llama:
  enabled: true
  weight: 1.0

vjepa-single:
  enabled: true
  weight: 1.0

vjepa-gpus:
  enabled: true
  weight: 1.0

resnet50:
  enabled: true
  weight: 1.0

convnext_large-tf32-fp16:
  enabled: true
  weight: 1.0

regnet_y_128gf:
  enabled: true
  weight: 1.0

dinov2-giant-gpus:
  enabled: true
  weight: 1.0

lightning-gpus:
  enabled: true
  weight: 1.0

diffusion-gpus:
  enabled: true
  weight: 1.0

diffusion-nodes:
  enabled: true
  weight: 2.0

llava-single:
  enabled: true
  weight: 1.0

ppo:
  enabled: true
  weight: 1.0

brax:
  enabled: true
  weight: 1.0

dqn:
  enabled: true
  weight: 1.0

rlhf-gpus:
  enabled: true
  weight: 2.0

pna:
  enabled: true
  weight: 1.0

dimenet:
  enabled: true
  weight: 1.0

recursiongfn:
  enabled: true
  weight: 1.0

##################
# Disabled tests #
##################

