include:
  - _defaults.yaml

_flops:
  inherits: _defaults
  definition: ../benchmarks/flops
  group: flops
  install_group: torch
  plan:
    method: per_gpu
  
  tags:
    - diagnostic
    - flops
    - monogpu
    - nobatch
  
  argv:
    --number: 10
    --repeat: 90


fp8:
  inherits: _flops

  argv:
    --number: 30
    --repeat: 90
    --m: 8192
    --n: 8192
    --dtype: fp8

fp16:
  inherits: _flops

  argv:
    --number: 30
    --repeat: 90
    --m: 8192
    --n: 8192
    --dtype: fp16

bf16:
  inherits: _flops
 
  argv:
    --m: 8192
    --n: 8192
    --dtype: bf16

tf32:
  inherits: _flops
 
  argv:
    --m: 8192
    --n: 8192
    --dtype: fp32
    --tf32: true

fp32:
  inherits: _flops
 
  argv:
    --m: 8192
    --n: 8192
    --dtype: fp32
