arch: cuda
sshkey: ~/.ssh/id_ed25519

nodes:
  - name: node1
    ip: 192.168.11.12
    port: 5000
    main: true
    user: worker1

  - name: node2
    ip: 192.168.11.13
    main: false 
    user: worker1
