
- hosts: database
  become: yes
  vars_files:
    - postgresqlconf.yml
  roles:
    - geerlingguy.postgresql

  
  tasks:
    - name: Create Tables
      ansible.builtin.debug:
        msg: Hello world
