_defaults:
  max_duration: 600
  voir:
    options:
      stop: 60
      interval: "1s"

test:
  inherits: _defaults
  group: test_remote
  install_group: test_remote
  definition: ../../benchmarks/_template
  plan:
    method: njobs
    n: 1

testing:
  inherits: _defaults
  definition: ../../benchmarks/_template
  group: test_remote_2
  install_group: test_remote_2
  plan:
    method: njobs
    n: 1
