[common]
dependencies = [
    "voir>=0.2.17,<0.3",
    "jax",
    "gymnax",
    "torch",
    "numpy",
    "gymnasium",
    "minatar",
    "wandb",
    "tensorboard",
    "flax",
    "optax",
    "distrax",
    "chex>=0.1.8",
    "rlax",
]

[cuda]
dependencies = [
    "jax[cuda{cuda_major}]",
]

[rocm]
dependencies = [
    "jax[rocm]",
]
enabled = true

[hpu]
enabled = false

[xpu]
enabled = false
