defaults: &defaults
  dirs:
    code: code/{name}
    venv: venv/{name}
    data: data
    runs: runs

  venv:
    type: virtualenv

  plan:
    method: njobs
    n: 1

  voir:
    # --stop: 10
    --forward:
      - "#stdout"
      - "#stderr"
      - "#end"
      - loss
      - compute_rate
      - train_rate
      - loading_rate
      - descr
      - progress
      - total
    --compute-rate: true
    --train-rate: true
    --loading-rate: true

  argv:
    --gpus: -1
    --max_epochs: 1
    --max_steps: 100
    --limit_val_batches: 100
    --devices: -1
    --enable_progress_bar: "False"
    --accelerator: "auto"

benchmarks:
  data-parallel:
    <<<: *defaults
    definition: ./
    argv:
      --backbone: "resnet152"
      --strategy: "dp"
      --profiler: "pytorch"
      --precision: 32

  model-parallel:
    <<<: *defaults
    definition: ./
    argv:
      --backbone: "vit_l_32"  # (larger model)
      --strategy: "fsdp"  # Fully-Sharded Data-Parallel
      # BUG: There appears to be some issues between FSDP and PyTorch profiler, script hangs.
      # --profiler: "pytorch"
      --profiler: "simple"
      --precision: 32

