defaults: &defaults
  dirs:
    code: ./_dev_torchvision
    venv: venv/torchvision
    data: data
    runs: runs

  venv:
    type: virtualenv

  plan:
    method: njobs
    n: 1

  voir:
    --stop: 10
    --forward:
      - "#stdout"
      - "#stderr"
      - "#end"
      - loss
      - compute_rate
      - train_rate
      - loading_rate
      - descr
      - progress
      - total
    --compute-rate: true
    --train-rate: true
    --loading-rate: true

  definition: ./

benchmarks:
  resnet18:
    <<<: *defaults
    argv:
      --model: resnet18
