# Run Milabench using nightly docker images
name: show-config

on:
  # Only works on manual runs
  workflow_dispatch:

jobs:
  execute:
    runs-on: [self-hosted, rocm]
    
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
  
    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
  
    - name: Show Pytorch Config
      run: |
        python -c "import torch; print(torch.__config__.show())"
  
